### PR TITLE
Fixed ValueError: time data does not match format

### PR DESCRIPTION
**Pull request by francutura**

### CODE REVIEW

**Comment by h-wata** [comment]
+1
- refs
 #1080 #1086

**Comment by Atcold** [comment]
@tommysolsen, can you please merge this one?
Three of us have already read and approved the code.

**Comment by tommysolsen** [comment]
Sure. I got no power to make a release however

**Comment by Atcold** [comment]
Hmm… The last release was in 2018.
I guess we simply have to install from the `develop` branch with `pip`.

**Pull request merged**
