### PR TITLE
Play an entire YouTube playlist command

### PR DESCRIPTION
**Pull request by danickfort**
* Allows playing an entire opened YT playlist with
    the double asterisk command "**".
    It essentially is a shortcut for the sequence:
      dump, *

### CODE REVIEW

**Comment by ids1024** [comment]
I think it might be best to make this the behavior of `*`/`all`, and get rid of the `dump` command. But that requires some other changes, such as loading additional pages in the background so it doesn't take forever to start playing. It would also make sense to have numbering start from the first page instead of restarting from one on every page.

I have been intending to do this, but it would take some time to implement. It would probably make sense to do after #423 which I have recently been working on is finished, since both involve replacing `g.model` with something else.

**Comment by danickfort** [comment]
Alright, sounds good. I'll close this for now then. Do you need some help on that new content API ? I'd love to help develop this project further.

**Comment by ids1024** [comment]
@danickfort Sure, help would definitely be appreciated.

**Comment by ids1024** [comment]
The dump command is now gone in the `content` branch, with behavior as I mentioned above. That branch is quite broken, and not really usable, but hopefully will be finished and merged before all too long (famous last words).

**Pull request closed without merging**
