### PR TITLE
Autoplay

### PR DESCRIPTION
**Pull request by nikhilweee**
I mostly use the program as a substitute for playing music on youtube. While working, this helps to kill silence and distraction. For such use case, selecting the next track manually defies the whole purpose. I hope there would be more people like me, so I added an autoplay feature.  

When a track finishes, this essentially searches for related tracks and randomly plays one among the top 15. This feature is optional and can be disabled via `set autoplay false` configuration command.

### CODE REVIEW

**Comment by orschiro** [comment]
Dear @nikhilweee,

This is brilliant. Thank you so much!

I just asked a related question here: https://askubuntu.com/questions/892505/how-can-i-auto-play-a-youtube-playlist-using-mps-youtube?noredirect=1#comment1396386_892505

I am using mps-youtube in the version 0.2.7.1. I guess your feature is not (yet) part of it. 

Could you please tell me how I can use your feature on Ubuntu 16.10?

Yours,

Robert

**Comment by nikhilweee** [comment]
Hi @orschiro!
You can use this feature by installing the development version. Either clone or download this repository, and run `./mpsyt` from the current directory. Install any missing dependencies and you should be able to use autoplay. Just `set autoplay on`.
However, in the question you want to autoplay a playlist, which is currently not supported. A close result could be acieved by playing the first related track. Replace `15` by `1` in `/mps_youtube/commands/play.py` `line 94`
Cheers,
Nikhil

**Comment by orschiro** [comment]
Thank you, Nikhil!

This is really great.

I appreciate your help.

Do you plan on supporting autoplay for playlists as well? :-)

Yours,

Robert

**Comment by nikhilweee** [comment]
@orschiro : I would love to do that but I'm currently short on time. I cannot make any promises at this moment. I'm really sorry about that.

**Comment by orschiro** [comment]
No problem. Thanks for your response!

**Comment by flocke** [comment]
@orschiro If all you want is simply to be able to play every video in one playlist automatically you can easily do this already with mps-youtube as it is. See my answer on your ask ubuntu post.

**Comment by orschiro** [comment]
I saw your response. This is excellent. Thank you!

**Pull request merged**
