### PR TITLE
Plugins

### PR DESCRIPTION
**Pull request by doriandimov**
Add automated conversion from .webm to .mp3 using 
> da # 
[webmp3.sh.zip](https://github.com/mps-youtube/mps-youtube/files/1027327/webmp3.sh.zip)

### CODE REVIEW

**Comment by ids1024** [comment]
> 	doriandimov  wants to merge 319 commits into dash from plugins

You pull requested the wrong branch. You want to pull request your fork into the `develop` branch.

**Comment by ids1024** [comment]
Or did you mean to submit an issue?

**Comment by doriandimov** [comment]
It is more like an issue than a fork, I don't think I could fork it. Sorry for pulling the wrong branch.

**Comment by Razesdark** [comment]
Since this was a spurious PR, we should probably close it

**Pull request closed without merging**
